import Head from 'next/head'
import { Inter } from '@next/font/google'
import Landing from '@/components/landing-page/landing'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}:any) {
  return (
    <>
      <Head>
        <title> Hade Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Landing image={data} />
      </div>
    </>
  )
}

export async function getStaticProps() {
  const {image} = await import('../data/images.json')

  return{
      props:{
          data: image,
      }
  }
}